package program_inventory_pbo;

import java.awt.Component;


/**
 *
 * @author arya
 */
public class MENU extends javax.swing.JFrame {

    /** Creates new form MENU */
    public MENU() {
        
                this.setTitle("Kede Aceh");

                initComponents();

                setExtendedState(MAXIMIZED_BOTH);
            }
    
    public void addCentered(Component test) {
        test.setVisible(true);
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        labelmenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenutest = new javax.swing.JMenu();
        jMenuAdmin = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuDataBarang = new javax.swing.JMenuItem();
        jMenuSuplier = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuPembelian = new javax.swing.JMenuItem();
        jMenuPenjualan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuLaporan = new javax.swing.JMenuItem();
        Jmenu5 = new javax.swing.JMenu();
        jMenudeskripsi = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROGRAM WARUNG");

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        labelmenu.setFont(new java.awt.Font("Arial Black", 1, 70)); // NOI18N
        labelmenu.setForeground(new java.awt.Color(255, 255, 255));
        labelmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelmenu.setText("Dashboard ");
        labelmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        labelmenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenutest.setText("File");
        jMenutest.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenutest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenutestActionPerformed(evt);
            }
        });

        jMenuAdmin.setText("Admin");
        jMenuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAdminMouseClicked(evt);
            }
        });
        jMenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdminActionPerformed(evt);
            }
        });
        jMenutest.add(jMenuAdmin);

        jMenuLogout.setText("Logout");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenutest.add(jMenuLogout);

        jMenuBar1.add(jMenutest);

        jMenu2.setText("Master Data");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jMenuDataBarang.setText("Data Barang");
        jMenuDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDataBarangActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuDataBarang);

        jMenuSuplier.setText("Suplier");
        jMenuSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuplierActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSuplier);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jMenuPembelian.setText("Pembelian");
        jMenuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPembelianActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuPembelian);

        jMenuPenjualan.setText("Penjualan");
        jMenuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuPenjualan);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jMenuLaporan.setText("Cetak Laporan");
        jMenuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLaporanActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuLaporan);

        jMenuBar1.add(jMenu4);

        Jmenu5.setText("About");
        Jmenu5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jMenudeskripsi.setText("Deskripsi");
        jMenudeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenudeskripsiActionPerformed(evt);
            }
        });
        Jmenu5.add(jMenudeskripsi);

        jMenuBar1.add(Jmenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAdminMouseClicked
        // TODO add your handling code here:
             
    }//GEN-LAST:event_jMenuAdminMouseClicked

    private void jMenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdminActionPerformed
        // TODO add your handling code here:
        labelmenu.removeAll();
        labelmenu.repaint();
        ADMIN OPEN = new ADMIN();
        OPEN.setVisible(true);
        labelmenu.add(OPEN);    
    }//GEN-LAST:event_jMenuAdminActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        LOGIN OPEN = new LOGIN();
        OPEN.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenutestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenutestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenutestActionPerformed

    private void jMenuSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuplierActionPerformed
        // TODO add your handling code here:
        labelmenu.removeAll();
        labelmenu.repaint();
        SUPLIER OPEN = new SUPLIER();
        OPEN.setVisible(true);
        labelmenu.add(OPEN);
    }//GEN-LAST:event_jMenuSuplierActionPerformed

    private void jMenuDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDataBarangActionPerformed
        // TODO add your handling code here:
        labelmenu.removeAll();
        labelmenu.repaint();
        DATA_BARANG OPEN = new DATA_BARANG();
        OPEN.setVisible(true);
        labelmenu.add(OPEN);
    }//GEN-LAST:event_jMenuDataBarangActionPerformed

    private void jMenuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPembelianActionPerformed
        // TODO add your handling code here:
        labelmenu.removeAll();
        labelmenu.repaint();
        PEMBELIAN OPEN = new PEMBELIAN();
        OPEN.setVisible(true);
        labelmenu.add(OPEN);
    }//GEN-LAST:event_jMenuPembelianActionPerformed

    private void jMenuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPenjualanActionPerformed
        // TODO add your handling code here:
        labelmenu.removeAll();
        labelmenu.repaint();
        PENJUALAN OPEN = new PENJUALAN();
        OPEN.setVisible(true);
        labelmenu.add(OPEN);
    }//GEN-LAST:event_jMenuPenjualanActionPerformed

    private void jMenuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLaporanActionPerformed
        // TODO add your handling code here:
        labelmenu.removeAll();
        labelmenu.repaint();
        LAPORAN OPEN = new LAPORAN();
        OPEN.setVisible(true);
        labelmenu.add(OPEN);
    }//GEN-LAST:event_jMenuLaporanActionPerformed

    private void jMenudeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenudeskripsiActionPerformed
        // TODO add your handling code here:
        labelmenu.removeAll();
        labelmenu.repaint();
        DESKRIPSI OPEN = new DESKRIPSI();
        OPEN.setVisible(true);
        labelmenu.add(OPEN);
    }//GEN-LAST:event_jMenudeskripsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDataBarang;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuLaporan;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenuItem jMenuPembelian;
    private javax.swing.JMenuItem jMenuPenjualan;
    private javax.swing.JMenuItem jMenuSuplier;
    private javax.swing.JMenuItem jMenudeskripsi;
    private javax.swing.JMenu jMenutest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelmenu;
    // End of variables declaration//GEN-END:variables

}
